feat: auth pages added
humzahasan/Hunger-Pangs-Static pull request #3
Opened 2022-02-13 14:20 UTC by humzahasan

2022-02-13 14:47 UTC, archit7448 commented
looks good to merge  and amazing work.

2022-02-13 14:47 UTC, archit7448 approved these changes

2022-02-13 15:01 UTC, purohitdheeraj approved these changes

2022-02-13 16:51 UTC, bhushannaikaroskar requested changes
There are multiple suggestion so I would wait for changes. One key advice would be make good use of classes wherever required. On multiple places you have reused better avoid it.

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Login/login.css
> +}
A small suggestion here as you are making component library its better to use class files. Maybe name it .home-search-icon. even tough you are using it once it would make sense to provide class name. This is what personally I would have done but if you think it's good you can go ahead with this as well.

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Login/login.css
> +}
less than 1rem use px.

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Login/login.css
> +}
Maybe add this in utility class as you are just increasing width. It would be logical to even name it .width-100 and use it in login.

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Login/login.html
> +          /></a>
use alt attribute in images its a good practice

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Login/login.html
> +                  />
Don't put alt attribute blank I would suggest to go through all images to check whether you have set alt attribute.

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Register/register.css
> +}
I think you have define this same in Login.css as well. I would suggest rather make one class separately.

2022-02-13 16:51 UTC, bhushannaikaroskar commented on pages/Register/register.css
> +}
px conversion please

2022-02-13 16:51 UTC, bhushannaikaroskar commented on styles.css
> +}
This one same pack it in utilities class as width.

2022-02-13 20:19 UTC, bhushannaikaroskar approved these changes
Approving but do changes before merge.

2022-02-14 18:26 UTC, humzahasan commented
@bhushannaikaroskar please check!

2022-02-17 13:45 UTC, merged